Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import json
import pandas as pd
import numpy as np
import re
import nltk
import std_func

data_t = pd.read_csv("data/timeseries_data.csv")
data =  pd.read_csv("data/preprocessed.csv")
data_t.head(2)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 7>[0;34m()[0m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mre[39;00m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mnltk[39;00m
[0;32m----> 7[0m [38;5;28;01mimport[39;00m [38;5;21;01mstd_func[39;00m
[1;32m      9[0m data_t [38;5;241m=[39m pd[38;5;241m.[39mread_csv([38;5;124m"[39m[38;5;124mdata/timeseries_data.csv[39m[38;5;124m"[39m)
[1;32m     10[0m data [38;5;241m=[39m  pd[38;5;241m.[39mread_csv([38;5;124m"[39m[38;5;124mdata/preprocessed.csv[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'std_func'
ModuleNotFoundError: No module named 'std_func'

